#! /bin/bash

# version       0.2.0
# executed by   scripts that use `libbash`
# task          perform library initialization

# ### Provides Call Stack Information
#
# This function prints the call stack to identify where an error
# originated.
#
# This function will only print a call stack if the stack is
# deeper than 2, because otherwise the error did not originate
# in a function but at global scope.
#
# #### Special
# 
# Underscored functions are not unset at the end of the sourcing
# process, but they should only be used by `libbash` modules, not
# by applications / other libraries using `libbash`.
function __show_call_stack
{
  [[ ${#FUNCNAME[@]} -le 2 ]] && return 0

  local STACK_DEPTH CUTOFF
  CUTOFF=2
  STACK_DEPTH=$(( ${#FUNCNAME[@]} - CUTOFF ))

  printf '\ncall stack (most recent call first):\n' >&2
  for FUNCTION in "${FUNCNAME[@]:${CUTOFF}:${STACK_DEPTH}}"
  do
    printf "  %s\n" "${FUNCTION}" >&2
  done

  printf '\n' >&2
}

# ### Show an Error
#
# Indicates an error has happend in `libbash`.
#
# #### Special
# 
# Underscored functions are not unset at the end of the sourcing
# process, but they should only be used by `libbash` modules, not
# by applications / other libraries using `libbash`.
function __libbash_show_error
{
  printf "\e[0m[  \e[91mERROR\e[0m  ] %30s | \e[91m%s\e[0m\n" \
    "${SCRIPT:-${0}}" "${*}" >&2
}

# ### Show an Error and Exit
#
# Indicates an error has happend in `libbash`. Exits with exit code
# 1 afterwards.
#
# #### Special
# 
# Underscored functions are not unset at the end of the sourcing
# process, but they should only be used by `libbash` modules, not
# by applications / other libraries using `libbash`.
function __libbash_show_error_and_exit
{
  __libbash_show_error "${*}"
  __show_call_stack
  exit 1
}

# ### Perform Basic `libbash` Initialization
#
# Mostly sets corrects environment variables.
function basic_setup
{
  # ! export all variables here first, even if not
  # ! all modules are sourced to satisfy shellcheck
  # ! in applications that use `libbash`
  export CRI LOG_LEVEL LIBBASH_DIRECTORY SCRIPT

  LOG_LEVEL=${LOG_LEVEL:-inf}
  LIBBASH_DIRECTORY="$(dirname "${BASH_SOURCE[0]}")"
  SCRIPT='libbash init'
}

# ### Load a `libbash` Module
#
# Checks if the given modules is present (exits unsuccessfully)
# otherwise. Then loads the module by sourcing it.
function load_module
{
  [[ -z ${1+set} ]] && __libbash_show_error_and_exit "no module provided"

  local MODULE_PATH
  MODULE_PATH="${LIBBASH_DIRECTORY}/modules/${1}.sh"

  if [[ -e "${MODULE_PATH}" ]]
  then
    # shellcheck source=/dev/null
    source "${MODULE_PATH}"
  else
    __libbash_show_error_and_exit "module '${1:-}' not found"
  fi
}

# ### Go Through Arguments
#
# Iterates through arguments and calls `load_module` to
# load the corresponding module.
function source_files
{
  local MODULE
  for MODULE in "${@}"
  do
    load_module "${MODULE}"
  done

  unset load_module
}

# ### Provide Debug Information
#
# Shows some debug information that `libbash` has collected.
function debug_libbash
{
  notify 'deb' "Showing 'libbash' debug information"
  notify 'deb' "Call / source stack:"
  for (( INDEX=${#BASH_SOURCE[@]} - 1 ; INDEX>1 ; INDEX-- ))
  do
    printf "%45s%s\n" '' "${BASH_SOURCE[INDEX]}"
  done
}

# ### Fallback `notify`
#
# If the `log` module was not sourced, provide a fallback
# `notify` implementation, but onyl for `err` messages.
function setup_default_notify_error
{
  function notify
  {
    if [[ ${1:-} != 'err' ]]
    then
      __libbash_show_error_and_exit                         \
        "log module was not loaded but 'notify' was called" \
        "with log level not 'err'"                          \
        "(arguments were: ${*})"
      __show_call_stack
    fi

    shift 1
    __libbash_show_error "${*}"
  }
  export -f notify
}

# ### The Start of `libbash`
#
# This function calls the initialization routines for `libbash`
# in proper order. 
function libbash_main
{
  basic_setup
  source_files "${@}"

  if [[ ! $(type -t notify) == 'function' ]]
  then
    setup_default_notify_error
    return 0
  fi

  notify 'tra' "Finished 'libbash' initialization"
}

libbash_main "${@}"
unset basic_setup source_files setup_default_notify_error main
SCRIPT='none (global)'
