---
name: Unit Tests

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: ['**']

defaults:
  run:
    shell: bash

jobs:
  run-unit-tests:
    name: Run BATS
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive
      - name: Run test suite
        run: bash -c 'make test'
        env:
          CI: true
