---
name: Bash Unit Testing

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches: ['**']

defaults:
  run:
    shell: bash

jobs:
  run-unit-tests:
    name: Run BATS (Bash Automated Testing System)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      - name: Run test suite
        run: bash -c 'make tests'
